### PR TITLE
Document configuration

### LINKED ISSUE #1: Add Documentation for Configuration Options
This bot would greatly benefit from better documentation of the configuration options at `config.js`

### PR DESCRIPTION
**Pull request by megatank58**
Fixes #1 

I have documented configs if there is anything i missed or some changes you want please let me know

### CODE REVIEW

**Comment by d4mr** [comment]
Hi! Great work so far. I was thinking it would be more helpful if you could describe what each of the configuration heading actually means. So, for example, for `roles-message`, a short description could be "Configuration options for the message posted by the bot. Reacting to this message grants users with roles."

Just some additional information and description which helps users to understand better what each of the configuration options is for.

Also, can you use table markup for the configuration options? Example:

|Option|Description|
|--|----|
|title|The text for the title of the embed|

Additionally, I think it would make sense to add a seperate "Features" section to the documentation, where we could illustrate with screenshots. I will create another issue for this.

Thanks once again for contributing, and let me know if you need anything!

**Comment by megatank58** [comment]
alright i will format it in tables (didn't come to my mind earlier) and also add some description for it as you suggested

**Comment by megatank58** [comment]
I have formatted the data in tables and added some more info for configurations could you check it once?

**Comment by d4mr** [comment]
Could you update the casing for the properties please? And also use backticks for the properties.
Eg:
| Property | Description |
|--------  | --------------- |
| Category | The category of the channel |
| Name     | The name of the channel |

this should look like:

| Property | Description |
|--------  | --------------- |
| `category` | The category of the channel |
| `name`    | The name of the channel |

This adds some more clarity.

**Comment by megatank58** [comment]
> Could you update the casing for the properties please? And also use backticks for the properties.
> Eg:
> | Property | Description |
> |--------  | --------------- |
> | Category | The category of the channel |
> | Name     | The name of the channel |
> 
> this should look like:
> 
> | Property | Description |
> |--------  | --------------- |
> | `category` | The category of the channel |
> | `name`    | The name of the channel |
> 
> This adds some more clarity.

Ah i see what you mean, I'll do the changes

**Comment by megatank58** [comment]
I have implemented casing and backticks let me know if something needs implemented

**Comment by d4mr** [comment]
Great work!

**Comment by megatank58** [comment]
Could you add the `hacktoberfest-accepted` label so it counts for hacktoberfest 😅

**Comment by d4mr** [comment]
> A pull request is considered approved once it has an overall approving review from maintainers, or has been merged by maintainers, or has been given the 'hacktoberfest-accepted' label.

Don't think it should be necessary, since I have merged it, but I am doing it in any case. Let me know if you need anything else :smile:

**Pull request merged**
